# Generated by Django 2.0 on 2017-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_auto_20171215_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
