# Generated by Django 2.0 on 2017-12-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(blank=True, choices=[('fra', 'France'), ('ger', 'Germany'), ('ita', 'Italy'), ('spa', 'Spain'), ('eng', 'England')], max_length=3),
        ),
    ]
